import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import net.minecraft.util.ResourceLocation;

public class LangGenerator {
    private static final String modid = "spacemine";

    private static final String[] itemRegistryNames = new String[] {
            "spacemine:asteroid",
            "spacemine:large_asteroid",
            "spacemine:asteroid_belt",
            "spacemine:moon",
            "spacemine:planet",
            "spacemine:star",
            "spacemine:solar_system",
            "spacemine:dwarf_planet",
            "spacemine:brown_dwarf",
            "spacemine:white_dwarf",
            "spacemine:black_dwarf",
            "spacemine:black_hole",
            "spacemine:red_supergiant",
            "spacemine:supernova",
            "spacemine:neutron_star",
            "spacemine:pulsar",
            "spacemine:solar_system_cluster",
            "spacemine:galaxy",
            "spacemine:galaxy_cluster",
            "spacemine:universe",
            "spacemine:multiverse",
            "spacemine:super_massive_black_hole",
            "spacemine:asteroid_helmet",
            "spacemine:large_asteroid_helmet",
            "spacemine:asteroid_belt_helmet",
            "spacemine:moon_helmet",
            "spacemine:planet_helmet",
            "spacemine:star_helmet",
            "spacemine:solar_system_helmet",
            "spacemine:dwarf_planet_helmet",
            "spacemine:brown_dwarf_helmet",
            "spacemine:white_dwarf_helmet",
            "spacemine:black_dwarf_helmet",
            "spacemine:black_hole_helmet",
            "spacemine:red_supergiant_helmet",
            "spacemine:supernova_helmet",
            "spacemine:neutron_star_helmet",
            "spacemine:pulsar_helmet",
            "spacemine:solar_system_cluster_helmet",
            "spacemine:galaxy_helmet",
            "spacemine:galaxy_cluster_helmet",
            "spacemine:universe_helmet",
            "spacemine:multiverse_helmet",
            "spacemine:super_massive_black_hole_helmet",
            "spacemine:asteroid_chestplate",
            "spacemine:large_asteroid_chestplate",
            "spacemine:asteroid_belt_chestplate",
            "spacemine:moon_chestplate",
            "spacemine:planet_chestplate",
            "spacemine:star_chestplate",
            "spacemine:solar_system_chestplate",
            "spacemine:dwarf_planet_chestplate",
            "spacemine:brown_dwarf_chestplate",
            "spacemine:white_dwarf_chestplate",
            "spacemine:black_dwarf_chestplate",
            "spacemine:black_hole_chestplate",
            "spacemine:red_supergiant_chestplate",
            "spacemine:supernova_chestplate",
            "spacemine:neutron_star_chestplate",
            "spacemine:pulsar_chestplate",
            "spacemine:solar_system_cluster_chestplate",
            "spacemine:galaxy_chestplate",
            "spacemine:galaxy_cluster_chestplate",
            "spacemine:universe_chestplate",
            "spacemine:multiverse_chestplate",
            "spacemine:super_massive_black_hole_chestplate",
            "spacemine:asteroid_leggings",
            "spacemine:large_asteroid_leggings",
            "spacemine:asteroid_belt_leggings",
            "spacemine:moon_leggings",
            "spacemine:planet_leggings",
            "spacemine:star_leggings",
            "spacemine:solar_system_leggings",
            "spacemine:dwarf_planet_leggings",
            "spacemine:brown_dwarf_leggings",
            "spacemine:white_dwarf_leggings",
            "spacemine:black_dwarf_leggings",
            "spacemine:black_hole_leggings",
            "spacemine:red_supergiant_leggings",
            "spacemine:supernova_leggings",
            "spacemine:neutron_star_leggings",
            "spacemine:pulsar_leggings",
            "spacemine:solar_system_cluster_leggings",
            "spacemine:galaxy_leggings",
            "spacemine:galaxy_cluster_leggings",
            "spacemine:universe_leggings",
            "spacemine:multiverse_leggings",
            "spacemine:super_massive_black_hole_leggings",
            "spacemine:asteroid_boots",
            "spacemine:large_asteroid_boots",
            "spacemine:asteroid_belt_boots",
            "spacemine:moon_boots",
            "spacemine:planet_boots",
            "spacemine:star_boots",
            "spacemine:solar_system_boots",
            "spacemine:dwarf_planet_boots",
            "spacemine:brown_dwarf_boots",
            "spacemine:white_dwarf_boots",
            "spacemine:black_dwarf_boots",
            "spacemine:black_hole_boots",
            "spacemine:red_supergiant_boots",
            "spacemine:supernova_boots",
            "spacemine:neutron_star_boots",
            "spacemine:pulsar_boots",
            "spacemine:solar_system_cluster_boots",
            "spacemine:galaxy_boots",
            "spacemine:galaxy_cluster_boots",
            "spacemine:universe_boots",
            "spacemine:multiverse_boots",
            "spacemine:super_massive_black_hole_boots",
            "spacemine:shrink_laser",
            "spacemine:asteroid_sword",
            "spacemine:large_asteroid_sword",
            "spacemine:asteroid_belt_sword",
            "spacemine:moon_sword",
            "spacemine:planet_sword",
            "spacemine:star_sword",
            "spacemine:solar_system_sword",
            "spacemine:dwarf_planet_sword",
            "spacemine:brown_dwarf_sword",
            "spacemine:white_dwarf_sword",
            "spacemine:black_dwarf_sword",
            "spacemine:black_hole_sword",
            "spacemine:red_supergiant_sword",
            "spacemine:supernova_sword",
            "spacemine:neutron_star_sword",
            "spacemine:pulsar_sword",
            "spacemine:solar_system_cluster_sword",
            "spacemine:galaxy_sword",
            "spacemine:galaxy_cluster_sword",
            "spacemine:universe_sword",
            "spacemine:multiverse_sword",
            "spacemine:super_massive_black_hole_sword",
            "spacemine:spacemine_armor",
            "spacemine:spacemine_weapons",
            "spacemine:spacemine_edibles",
            "spacemine:spacemine_misc",
            "spacemine:spacemine_tools",
            "spacemine:asteroid_mattock",
            "spacemine:large_asteroid_mattock",
            "spacemine:asteroid_belt_mattock",
            "spacemine:moon_mattock",
            "spacemine:planet_mattock",
            "spacemine:star_mattock",
            "spacemine:solar_system_mattock",
            "spacemine:dwarf_planet_mattock",
            "spacemine:brown_dwarf_mattock",
            "spacemine:white_dwarf_mattock",
            "spacemine:black_dwarf_mattock",
            "spacemine:black_hole_mattock",
            "spacemine:red_supergiant_mattock",
            "spacemine:supernova_mattock",
            "spacemine:neutron_star_mattock",
            "spacemine:pulsar_mattock",
            "spacemine:solar_system_cluster_mattock",
            "spacemine:galaxy_mattock",
            "spacemine:galaxy_cluster_mattock",
            "spacemine:universe_mattock",
            "spacemine:multiverse_mattock",
            "spacemine:super_massive_black_hole_mattock"

    };

    public static void main(String[] args) {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        JsonObject object = new JsonObject();

        for (String itemRegistryName : itemRegistryNames) {
            ResourceLocation location = new ResourceLocation(itemRegistryName);
            object.addProperty("block." + location.getNamespace() + "." + location.getPath(), toName(location.getPath()));
        }

        System.out.println(gson.toJson(object));
    }

    public static final String toName(String src) {
        StringBuilder out = new StringBuilder();
        for (String s : src.split("_")) {
            out.append(s.substring(0, 1).toUpperCase()).append(s.substring(1)).append(" ");
        }
        return out.substring(0, out.length() - 1);
    }
}
