package anticookiestudios.spacemine;

import anticookiestudios.spacemine.items.SpacemineFoods;
import net.minecraft.block.Block;
import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.*;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.threetag.threecore.item.recipe.ToolIngredient;

import java.util.Set;


public class ItemRegistry {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, "spacemine");
    public static final RegistryObject<Item> ASTEROID = ITEMS.register("asteroid", () -> new SpacemineBlockItem(BlockRegistry.ASTEROID.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.ASTEROID).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> ASTEROID_SWORD = ITEMS.register("asteroid_sword", ()->new SpacemineSwordItem(SpacemineItemTier.ASTEROID, 4, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> ASTEROID_HELMET = ITEMS.register("asteroid_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_CHESTPLATE = ITEMS.register("asteroid_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_LEGGINGS = ITEMS.register("asteroid_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_BOOTS = ITEMS.register("asteroid_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_MATTOCK = ITEMS.register("asteroid_mattock", ()->new MattockToolItem(4, -2.4F, SpacemineItemTier.ASTEROID, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> LARGE_ASTEROID = ITEMS.register("large_asteroid", () -> new SpacemineBlockItem(BlockRegistry.LARGE_ASTEROID.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.LARGE_ASTEROID).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> LARGE_ASTEROID_SWORD = ITEMS.register("large_asteroid_sword", ()->new SpacemineSwordItem(SpacemineItemTier.LARGE_ASTEROID, 9, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> LARGE_ASTEROID_HELMET = ITEMS.register("large_asteroid_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.LARGE_ASTEROID, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> LARGE_ASTEROID_CHESTPLATE = ITEMS.register("large_asteroid_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.LARGE_ASTEROID, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> LARGE_ASTEROID_LEGGINGS = ITEMS.register("large_asteroid_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.LARGE_ASTEROID, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> LARGE_ASTEROID_BOOTS = ITEMS.register("large_asteroid_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.LARGE_ASTEROID, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> LARGE_ASTEROID_MATTOCK = ITEMS.register("large_asteroid_mattock", ()->new MattockToolItem(9, -2.4F, SpacemineItemTier.LARGE_ASTEROID, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> ASTEROID_BELT = ITEMS.register("asteroid_belt", () -> new SpacemineBlockItem(BlockRegistry.ASTEROID_BELT.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.ASTEROID_BELT).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> ASTEROID_BELT_SWORD = ITEMS.register("asteroid_belt_sword", ()->new SpacemineSwordItem(SpacemineItemTier.ASTEROID_BELT, 9, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> ASTEROID_BELT_HELMET = ITEMS.register("asteroid_belt_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID_BELT, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_BELT_CHESTPLATE = ITEMS.register("asteroid_belt_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID_BELT, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_BELT_LEGGINGS = ITEMS.register("asteroid_belt_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID_BELT, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_BELT_BOOTS = ITEMS.register("asteroid_belt_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.ASTEROID_BELT, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> ASTEROID_BELT_MATTOCK = ITEMS.register("asteroid_belt_mattock", ()->new MattockToolItem(9, -2.4F, SpacemineItemTier.ASTEROID_BELT, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> MOON = ITEMS.register("moon", () -> new SpacemineBlockItem(BlockRegistry.MOON.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.MOON).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> MOON_SWORD = ITEMS.register("moon_sword", ()->new SpacemineSwordItem(SpacemineItemTier.MOON, 16, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> MOON_HELMET = ITEMS.register("moon_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MOON, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MOON_CHESTPLATE = ITEMS.register("moon_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MOON, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MOON_LEGGINGS = ITEMS.register("moon_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MOON, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MOON_BOOTS = ITEMS.register("moon_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MOON, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MOON_MATTOCK = ITEMS.register("moon_mattock", ()->new MattockToolItem(16, -2.4F, SpacemineItemTier.MOON, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> PLANET = ITEMS.register("planet", () -> new SpacemineBlockItem(BlockRegistry.PLANET.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.PLANET).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> PLANET_SWORD = ITEMS.register("planet_sword", ()->new SpacemineSwordItem(SpacemineItemTier.PLANET, 16, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> PLANET_HELMET = ITEMS.register("planet_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PLANET, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PLANET_CHESTPLATE = ITEMS.register("planet_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PLANET, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PLANET_LEGGINGS = ITEMS.register("planet_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PLANET, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PLANET_BOOTS = ITEMS.register("planet_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PLANET, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PLANET_MATTOCK = ITEMS.register("planet_mattock", ()->new MattockToolItem(16, -2.4F, SpacemineItemTier.PLANET, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> STAR = ITEMS.register("star", () -> new SpacemineBlockItem(BlockRegistry.STAR.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.STAR).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> STAR_SWORD = ITEMS.register("star_sword", ()->new SpacemineSwordItem(SpacemineItemTier.STAR, 30, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> STAR_HELMET = ITEMS.register("star_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.STAR, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> STAR_CHESTPLATE = ITEMS.register("star_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.STAR, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> STAR_LEGGINGS = ITEMS.register("star_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.STAR, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> STAR_BOOTS = ITEMS.register("star_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.STAR, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> STAR_MATTOCK = ITEMS.register("star_mattock", ()->new MattockToolItem(30, -2.4F, SpacemineItemTier.STAR, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> SOLAR_SYSTEM = ITEMS.register("solar_system", () -> new SpacemineBlockItem(BlockRegistry.SOLAR_SYSTEM.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.SOLAR_SYSTEM).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_SWORD = ITEMS.register("solar_system_sword", ()->new SpacemineSwordItem(SpacemineItemTier.SOLAR_SYSTEM, 51, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_HELMET = ITEMS.register("solar_system_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_CHESTPLATE = ITEMS.register("solar_system_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_LEGGINGS = ITEMS.register("solar_system_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_BOOTS = ITEMS.register("solar_system_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_MATTOCK = ITEMS.register("solar_system_mattock", ()->new MattockToolItem(30, -2.4F, SpacemineItemTier.SOLAR_SYSTEM, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> DWARF_PLANET = ITEMS.register("dwarf_planet", () -> new SpacemineBlockItem(BlockRegistry.DWARF_PLANET.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.DWARF_PLANET).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> DWARF_PLANET_SWORD = ITEMS.register("dwarf_planet_sword", ()->new SpacemineSwordItem(SpacemineItemTier.DWARF_PLANET, 30, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> DWARF_PLANET_HELMET = ITEMS.register("dwarf_planet_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.DWARF_PLANET, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> DWARF_PLANET_CHESTPLATE = ITEMS.register("dwarf_planet_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.DWARF_PLANET, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> DWARF_PLANET_LEGGINGS = ITEMS.register("dwarf_planet_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.DWARF_PLANET, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> DWARF_PLANET_BOOTS = ITEMS.register("dwarf_planet_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.DWARF_PLANET, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> DWARF_PLANET_MATTOCK = ITEMS.register("dwarf_planet_mattock", ()->new MattockToolItem(30, -2.4F, SpacemineItemTier.DWARF_PLANET, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> BROWN_DWARF = ITEMS.register("brown_dwarf", () -> new SpacemineBlockItem(BlockRegistry.BROWN_DWARF.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.BROWN_DWARF).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> BROWN_DWARF_SWORD = ITEMS.register("brown_dwarf_sword", ()->new SpacemineSwordItem(SpacemineItemTier.BROWN_DWARF, 51, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> BROWN_DWARF_HELMET = ITEMS.register("brown_dwarf_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BROWN_DWARF, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BROWN_DWARF_CHESTPLATE = ITEMS.register("brown_dwarf_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BROWN_DWARF, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BROWN_DWARF_LEGGINGS = ITEMS.register("brown_dwarf_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BROWN_DWARF, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BROWN_DWARF_BOOTS = ITEMS.register("brown_dwarf_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BROWN_DWARF, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BROWN_DWARF_MATTOCK = ITEMS.register("brown_dwarf_mattock", ()->new MattockToolItem(51, -2.4F, SpacemineItemTier.BROWN_DWARF, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> WHITE_DWARF = ITEMS.register("white_dwarf", () -> new SpacemineBlockItem(BlockRegistry.WHITE_DWARF.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.WHITE_DWARF).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> WHITE_DWARF_SWORD = ITEMS.register("white_dwarf_sword", ()->new SpacemineSwordItem(SpacemineItemTier.WHITE_DWARF, 51, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> WHITE_DWARF_HELMET = ITEMS.register("white_dwarf_helmet", ()->new WhiteDwarfArmorItem(SpacemineArmorMaterial.WHITE_DWARF, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> WHITE_DWARF_CHESTPLATE = ITEMS.register("white_dwarf_chestplate", ()->new WhiteDwarfArmorItem(SpacemineArmorMaterial.WHITE_DWARF, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> WHITE_DWARF_LEGGINGS = ITEMS.register("white_dwarf_leggings", ()->new WhiteDwarfArmorItem(SpacemineArmorMaterial.WHITE_DWARF, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> WHITE_DWARF_BOOTS = ITEMS.register("white_dwarf_boots", ()->new WhiteDwarfArmorItem(SpacemineArmorMaterial.WHITE_DWARF, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> WHITE_DWARF_MATTOCK = ITEMS.register("white_dwarf_mattock", ()->new MattockToolItem(51, -2.4F, SpacemineItemTier.WHITE_DWARF, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> BLACK_DWARF = ITEMS.register("black_dwarf", () -> new SpacemineBlockItem(BlockRegistry.BLACK_DWARF.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.BLACK_DWARF).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> BLACK_DWARF_SWORD = ITEMS.register("black_dwarf_sword", ()->new SpacemineSwordItem(SpacemineItemTier.BLACK_DWARF, 84, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> BLACK_DWARF_HELMET = ITEMS.register("black_dwarf_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BLACK_DWARF, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_DWARF_CHESTPLATE = ITEMS.register("black_dwarf_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BLACK_DWARF, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_DWARF_LEGGINGS = ITEMS.register("black_dwarf_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BLACK_DWARF, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_DWARF_BOOTS = ITEMS.register("black_dwarf_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.BLACK_DWARF, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_DWARF_MATTOCK = ITEMS.register("black_dwarf_mattock", ()->new MattockToolItem(84, -2.4F, SpacemineItemTier.BLACK_DWARF, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> BLACK_HOLE = ITEMS.register("black_hole", () -> new SpacemineBlockItem(BlockRegistry.BLACK_HOLE.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.BLACK_HOLE).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> BLACK_HOLE_SWORD = ITEMS.register("black_hole_sword", ()->new SpacemineSwordItem(SpacemineItemTier.BLACK_HOLE, 138, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> BLACK_HOLE_HELMET = ITEMS.register("black_hole_helmet", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.BLACK_HOLE, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_HOLE_CHESTPLATE = ITEMS.register("black_hole_chestplate", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.BLACK_HOLE, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_HOLE_LEGGINGS = ITEMS.register("black_hole_leggings", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.BLACK_HOLE, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_HOLE_BOOTS = ITEMS.register("black_hole_boots", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.BLACK_HOLE, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> BLACK_HOLE_MATTOCK = ITEMS.register("black_hole_mattock", ()->new MattockToolItem(138, -2.4F, SpacemineItemTier.BLACK_HOLE, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> RED_SUPERGIANT = ITEMS.register("red_supergiant", () -> new SpacemineBlockItem(BlockRegistry.RED_SUPERGIANT.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.RED_SUPERGIANT).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> RED_SUPERGIANT_SWORD = ITEMS.register("red_supergiant_sword", ()->new SpacemineSwordItem(SpacemineItemTier.RED_SUPERGIANT, 51, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> RED_SUPERGIANT_HELMET = ITEMS.register("red_supergiant_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.RED_SUPERGIANT, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> RED_SUPERGIANT_CHESTPLATE = ITEMS.register("red_supergiant_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.RED_SUPERGIANT, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> RED_SUPERGIANT_LEGGINGS = ITEMS.register("red_supergiant_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.RED_SUPERGIANT, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> RED_SUPERGIANT_BOOTS = ITEMS.register("red_supergiant_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.RED_SUPERGIANT, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> RED_SUPERGIANT_MATTOCK = ITEMS.register("red_supergiant_mattock", ()->new MattockToolItem(51, -2.4F, SpacemineItemTier.RED_SUPERGIANT, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> SUPERNOVA = ITEMS.register("supernova", () -> new SpacemineBlockItem(BlockRegistry.SUPERNOVA.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.SUPERNOVA).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> SUPERNOVA_SWORD = ITEMS.register("supernova_sword", ()->new SpacemineSwordItem(SpacemineItemTier.SUPERNOVA, 84, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> SUPERNOVA_HELMET = ITEMS.register("supernova_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SUPERNOVA, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SUPERNOVA_CHESTPLATE = ITEMS.register("supernova_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SUPERNOVA, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SUPERNOVA_LEGGINGS = ITEMS.register("supernova_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SUPERNOVA, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SUPERNOVA_BOOTS = ITEMS.register("supernova_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SUPERNOVA, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SUPERNOVA_MATTOCK = ITEMS.register("supernova_mattock", ()->new MattockToolItem(84, -2.4F, SpacemineItemTier.SUPERNOVA, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> NEUTRON_STAR = ITEMS.register("neutron_star", () -> new SpacemineBlockItem(BlockRegistry.NEUTRON_STAR.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.NEUTRON_STAR).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> NEUTRON_STAR_SWORD = ITEMS.register("neutron_star_sword", ()->new SpacemineSwordItem(SpacemineItemTier.NEUTRON_STAR, 138, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> NEUTRON_STAR_HELMET = ITEMS.register("neutron_star_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.NEUTRON_STAR, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> NEUTRON_STAR_CHESTPLATE = ITEMS.register("neutron_star_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.NEUTRON_STAR, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> NEUTRON_STAR_LEGGINGS = ITEMS.register("neutron_star_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.NEUTRON_STAR, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> NEUTRON_STAR_BOOTS = ITEMS.register("neutron_star_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.NEUTRON_STAR, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> NEUTRON_STAR_MATTOCK = ITEMS.register("neutron_star_mattock", ()->new MattockToolItem(138, -2.4F, SpacemineItemTier.NEUTRON_STAR, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> PULSAR = ITEMS.register("pulsar", () -> new SpacemineBlockItem(BlockRegistry.PULSAR.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.PULSAR).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> PULSAR_SWORD = ITEMS.register("pulsar_sword", ()->new SpacemineSwordItem(SpacemineItemTier.PULSAR, 226, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> PULSAR_HELMET = ITEMS.register("pulsar_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PULSAR, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PULSAR_CHESTPLATE = ITEMS.register("pulsar_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PULSAR, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PULSAR_LEGGINGS = ITEMS.register("pulsar_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PULSAR, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PULSAR_BOOTS = ITEMS.register("pulsar_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.PULSAR, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> PULSAR_MATTOCK = ITEMS.register("pulsar_mattock", ()->new MattockToolItem(226, -2.4F, SpacemineItemTier.PULSAR, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> SOLAR_SYSTEM_CLUSTER = ITEMS.register("solar_system_cluster", () -> new SpacemineBlockItem(BlockRegistry.SOLAR_SYSTEM_CLUSTER.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.SOLAR_SYSTEM_CLUSTER).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_CLUSTER_SWORD = ITEMS.register("solar_system_cluster_sword", ()->new SpacemineSwordItem(SpacemineItemTier.SOLAR_SYSTEM_CLUSTER, 84, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_CLUSTER_HELMET = ITEMS.register("solar_system_cluster_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM_CLUSTER, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_CLUSTER_CHESTPLATE = ITEMS.register("solar_system_cluster_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM_CLUSTER, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_CLUSTER_LEGGINGS = ITEMS.register("solar_system_cluster_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM_CLUSTER, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_CLUSTER_BOOTS = ITEMS.register("solar_system_cluster_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.SOLAR_SYSTEM_CLUSTER, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SOLAR_SYSTEM_CLUSTER_MATTOCK = ITEMS.register("solar_system_cluster_mattock", ()->new MattockToolItem(84, -2.4F, SpacemineItemTier.SOLAR_SYSTEM_CLUSTER, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> GALAXY = ITEMS.register("galaxy", () -> new SpacemineBlockItem(BlockRegistry.GALAXY.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.GALAXY).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> GALAXY_SWORD = ITEMS.register("galaxy_sword", ()->new SpacemineSwordItem(SpacemineItemTier.GALAXY, 138, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> GALAXY_HELMET = ITEMS.register("galaxy_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_CHESTPLATE = ITEMS.register("galaxy_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_LEGGINGS = ITEMS.register("galaxy_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_BOOTS = ITEMS.register("galaxy_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_MATTOCK = ITEMS.register("galaxy_mattock", ()->new MattockToolItem(138, -2.4F, SpacemineItemTier.GALAXY, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> GALAXY_CLUSTER = ITEMS.register("galaxy_cluster", () -> new SpacemineBlockItem(BlockRegistry.GALAXY_CLUSTER.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.GALAXY_CLUSTER).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> GALAXY_CLUSTER_SWORD = ITEMS.register("galaxy_cluster_sword", ()->new SpacemineSwordItem(SpacemineItemTier.GALAXY_CLUSTER, 226, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> GALAXY_CLUSTER_HELMET = ITEMS.register("galaxy_cluster_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY_CLUSTER, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_CLUSTER_CHESTPLATE = ITEMS.register("galaxy_cluster_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY_CLUSTER, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_CLUSTER_LEGGINGS = ITEMS.register("galaxy_cluster_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY_CLUSTER, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_CLUSTER_BOOTS = ITEMS.register("galaxy_cluster_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.GALAXY_CLUSTER, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> GALAXY_CLUSTER_MATTOCK = ITEMS.register("galaxy_cluster_mattock", ()->new MattockToolItem(226, -2.4F, SpacemineItemTier.GALAXY_CLUSTER, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> UNIVERSE = ITEMS.register("universe", () -> new SpacemineBlockItem(BlockRegistry.UNIVERSE.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.UNIVERSE).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> UNIVERSE_SWORD = ITEMS.register("universe_sword", ()->new SpacemineSwordItem(SpacemineItemTier.UNIVERSE, 368, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> UNIVERSE_HELMET = ITEMS.register("universe_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.UNIVERSE, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> UNIVERSE_CHESTPLATE = ITEMS.register("universe_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.UNIVERSE, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> UNIVERSE_LEGGINGS = ITEMS.register("universe_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.UNIVERSE, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> UNIVERSE_BOOTS = ITEMS.register("universe_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.UNIVERSE, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> UNIVERSE_MATTOCK = ITEMS.register("universe_mattock", ()->new MattockToolItem(368, -2.4F, SpacemineItemTier.UNIVERSE, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> MULTIVERSE = ITEMS.register("multiverse", () -> new SpacemineBlockItem(BlockRegistry.MULTIVERSE.get(), new Item.Properties().maxStackSize(64).food(SpacemineFoods.MULTIVERSE).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> MULTIVERSE_SWORD = ITEMS.register("multiverse_sword", ()->new SpacemineSwordItem(SpacemineItemTier.MULTIVERSE, 596, -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> MULTIVERSE_HELMET = ITEMS.register("multiverse_helmet", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MULTIVERSE, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MULTIVERSE_CHESTPLATE = ITEMS.register("multiverse_chestplate", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MULTIVERSE, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MULTIVERSE_LEGGINGS = ITEMS.register("multiverse_leggings", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MULTIVERSE, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MULTIVERSE_BOOTS = ITEMS.register("multiverse_boots", ()->new SpacemineArmorItem(SpacemineArmorMaterial.MULTIVERSE, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> MULTIVERSE_MATTOCK = ITEMS.register("multiverse_mattock", ()->new MattockToolItem(596, -2.4F, SpacemineItemTier.MULTIVERSE, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> SUPER_MASSIVE_BLACK_HOLE = ITEMS.register("super_massive_black_hole", () -> new SpacemineBlockItem(BlockRegistry.SUPER_MASSIVE_BLACK_HOLE.get(), new Item.Properties().food(SpacemineFoods.SUPER_MASSIVE_BLACK_HOLE).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_EDIBLES)));
    public static final RegistryObject<Item> SUPER_MASSIVE_BLACK_HOLE_SWORD = ITEMS.register("super_massive_black_hole_sword", ()->new SpacemineSwordItem(SpacemineItemTier.SUPER_MASSIVE_BLACK_HOLE,226 , -2.4F, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_WEAPONS)));
    public static final RegistryObject<Item> SUPER_MASSIVE_BLACK_HOLE_HELMET = ITEMS.register("super_massive_black_hole_helmet", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.SUPER_MASSIVE_BLACK_HOLE, EquipmentSlotType.HEAD, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SUPER_MASSIVE_BLACK_HOLE_CHESTPLATE = ITEMS.register("super_massive_black_hole_chestplate", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.SUPER_MASSIVE_BLACK_HOLE, EquipmentSlotType.CHEST, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SUPER_MASSIVE_BLACK_HOLE_LEGGINGS = ITEMS.register("super_massive_black_hole_leggings", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.SUPER_MASSIVE_BLACK_HOLE, EquipmentSlotType.LEGS, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SUPER_MASSIVE_BLACK_HOLE_BOOTS = ITEMS.register("super_massive_black_hole_boots", ()->new BlackHoleArmorItem(SpacemineArmorMaterial.SUPER_MASSIVE_BLACK_HOLE, EquipmentSlotType.FEET, (new Item.Properties()).maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_ARMOR)));
    public static final RegistryObject<Item> SHRINK_LASER_ASTEROID = ITEMS.register("shrink_laser_asteroid", () -> new SpacemineBlockItem(BlockRegistry.SHRINK_LASER.get(), new Item.Properties().maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_MISC)));
    public static final RegistryObject<Item> SUPER_MASSIVE_BLACK_HOLE_MATTOCK = ITEMS.register("super_massive_black_hole_mattock", ()->new MattockToolItem(226, -2.4F, SpacemineItemTier.SUPER_MASSIVE_BLACK_HOLE, (new Item.Properties()).maxStackSize(1).group(SpacemineItemGroup.SPACEMINE_TOOLS)));

    public static final RegistryObject<Item> SHRINK_LASER_PLANET = ITEMS.register("shrink_laser_planet", () -> new SpacemineBlockItem(BlockRegistry.SHRINK_LASER_1.get(), new Item.Properties().maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_MISC)));
    public static final RegistryObject<Item> SHRINK_LASER_RED_SUPERGIANT = ITEMS.register("shrink_laser_red_supergiant", () -> new SpacemineBlockItem(BlockRegistry.SHRINK_LASER_2.get(), new Item.Properties().maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_MISC)));
    public static final RegistryObject<Item> SHRINK_LASER_BLACK_HOLE = ITEMS.register("shrink_laser_black_hole", () -> new SpacemineBlockItem(BlockRegistry.SHRINK_LASER_3.get(), new Item.Properties().maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_MISC)));
    public static final RegistryObject<Item> SHRINK_LASER_GALAXY = ITEMS.register("shrink_laser_galaxy", () -> new SpacemineBlockItem(BlockRegistry.SHRINK_LASER_4.get(), new Item.Properties().maxStackSize(64).group(SpacemineItemGroup.SPACEMINE_MISC)));
    //y=8(1.6156234212)^{x}
    public static final RegistryObject<Item> SPACE_PUFFERFISH = ITEMS.register("space_pufferfish", () -> new Item(new Item.Properties().maxStackSize(64).food(SpacemineFoods.SPACE_PUFFERFISH).group(SpacemineItemGroup.SPACEMINE_MISC)));
    public static final RegistryObject<Item> ANTIMATTER = ITEMS.register("antimatter", () -> new Item(new Item.Properties().maxStackSize(1).food(SpacemineFoods.ANTIMATTER).group(SpacemineItemGroup.SPACEMINE_MISC)));

}
